name: multi builds

on:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true

jobs:
  test1:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    name: test1
    steps:
    - name: checkout the code
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.workflow_run.head_branch }}

  test2:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    name: test2
    steps:
    - name: checkout the code test2
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.workflow_run.head_branch }}


  deploy1:
    needs: test1
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    name: deploy test1
    steps:
    - name: checkout test1
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.workflow_run.head_branch }}


  deploy2:
    needs: [ deploy1, test2 ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    name: deploy test2
    steps:
    - name: checkout test2
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.workflow_run.head_branch }}


      
